version: '3'
services:
# The Database

    dbdata:
        container_name: mysql_database
        image: mysql:8.0
        restart: unless-stopped

        volumes:
            - ./docker-compose/dev/mysql:/docker-entrypoint-initdb.d

        environment:

            - “MYSQL_USER=root”

            - “MYSQL_PASSWORD=”

            - "MYSQL_ALLOW_EMPTY_PASSWORD=true"

        ports:

            - 3300:3300

    nginx:
        image: nginx:1.17-alpine
        container_name: recetify-nginx
        restart: unless-stopped
        ports:
            - 8081:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d


#The Application

    app:
        image: recetify_app
        container_name: recetify_app
        command: sh -c "php artisan storage:link && php artisan octane:start --watch --server=\"swoole\" --host=0.0.0.0 --port=9000"

        build:

            context: ./

            dockerfile: dockerfile
            args:
                user: Danny
                uid: 1000

        volumes:
            - ./app:/var/www/app
            - ./config:/var/www/config
            - ./database:/var/www/database
            - ./graphql:/var/www/graphql
            - ./routes:/var/www/routes
            - ./resources:/var/www/resources
            - ./tests:/var/www/test
            - ./storage:/var/www/storage
            - ./public:/var/www/public
            - ./composer.lock:/var/www/composer.lock
            - ./composer.json:/var/www/composer.json
        env_file: .env

        ports:
            - 9000:9501
